### ISSUE TITLE
16.11 react无法使用

### ISSUE THREAD

**Issue by jinjin123** [guhuaijin/react-code-diff#6]
`./node_modules/react-code-diff/index.jsx 16:15
Module parse failed: Unexpected token (16:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|     render (){
>         return <div id="code-diff" dangerouslySetInnerHTML={{__html: this.html()}}></div>;
|     }
|`

**Comment by AmazingK64** [comment]
请问该问题最后解决了吗

**Comment by jinjin123** [comment]
> 请问该问题最后解决了吗

没， 换工具库了
